# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-postgresql-cve-2021-3677-unauthorized-modication-log-file
  namespace: database
spec:
  tags: ["PostgreSQL", "logs","postgresql"] 
  message: "Modification in Log File of PostgreSQL "
  selector:
    matchLabels:
      db: myPostgresqlDB
  file:
    severity: 4
    matchDirectories:
      - dir: /var/log/postgresql/
        recursive: true
        readOnly: false
        fromSource:
        - path: /usr/bin/touch
        - path: /usr/bin/chmod
        - path: /usr/bin/nano
        - path: /usr/bin/cat
    action: Block
    
